// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaWgtnxCZqJN_rR57jT7u6rr3AnLGPxFI',
    appId: '1:878403433657:web:4441f207ac8eeca77b1768',
    messagingSenderId: '878403433657',
    projectId: 'hangout-4a0f7',
    authDomain: 'hangout-4a0f7.firebaseapp.com',
    storageBucket: 'hangout-4a0f7.firebasestorage.app',
    measurementId: 'G-ZPVP7W9DM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQsgxyHnvNYFqHp6QVCugOBegO9USoO7g',
    appId: '1:878403433657:android:b1977049610812707b1768',
    messagingSenderId: '878403433657',
    projectId: 'hangout-4a0f7',
    storageBucket: 'hangout-4a0f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkfmJGmKYyL9CRx9gv1T4b0J5mUizn1rg',
    appId: '1:878403433657:ios:e96f3c565b26a7567b1768',
    messagingSenderId: '878403433657',
    projectId: 'hangout-4a0f7',
    storageBucket: 'hangout-4a0f7.firebasestorage.app',
    iosBundleId: 'com.example.hangout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkfmJGmKYyL9CRx9gv1T4b0J5mUizn1rg',
    appId: '1:878403433657:ios:e96f3c565b26a7567b1768',
    messagingSenderId: '878403433657',
    projectId: 'hangout-4a0f7',
    storageBucket: 'hangout-4a0f7.firebasestorage.app',
    iosBundleId: 'com.example.hangout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaWgtnxCZqJN_rR57jT7u6rr3AnLGPxFI',
    appId: '1:878403433657:web:a002915116ea582b7b1768',
    messagingSenderId: '878403433657',
    projectId: 'hangout-4a0f7',
    authDomain: 'hangout-4a0f7.firebaseapp.com',
    storageBucket: 'hangout-4a0f7.firebasestorage.app',
    measurementId: 'G-0ZX6EZD1ZH',
  );

}